# -*- coding: utf-8 -*-
"""Tugas Akhir BST

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lXWPeIWPh0MJlR2Vw2DshLFcw_4Lk61M

# Study Case 6✨

Dalam dunia hiburan, industri film memiliki peran penting dalam membawa cerita dan emosi kepada penonton. Dataset "IMDb Indonesian Movies" berisi kumpulan ulasan film dari berbagai pengguna yang diungkapkan dalam kata-kata. Seorang analis data bernama Ethan bersemangat untuk mengeksplorasi dataset ini dan melakukan analisis sentimen untuk memahami bagaimana penonton merespons film-film yang berbeda. Pertanyaan :

Menghubungkan file CSV ke *Google Collab.*
"""

from google.colab import drive
drive.mount("/content/drive")

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

path="/content/drive/MyDrive/Dataset/indonesian_movies.csv"
df=pd.read_csv(path)
df.head(10)

"""# Point A

Bagaimana distribusi genre film dalam dataset ini? Buat bar chart untuk memvisualisasikan genre-genre yang ada.
"""

# Menghapus baris dengan nilai-nilai genre yang hilang
df = df.dropna(subset=['genre'])

# Memisahkan string genre menjadi list
df['genre'] = df['genre'].str.split(',')

# Create a set to store unique genres
unique_genres = set()

# Iterate through each row and add genres to the set
for genres in df['genre']:
    unique_genres.update(genres)

# Convert the set to a sorted list
sorted_unique_genres = sorted(unique_genres)

# Count occurrences of each genre
genre_count = {genre: 0 for genre in sorted_unique_genres}
for genres in df['genre']:
    for genre in genres:
        genre_count[genre] += 1

# Convert genre_count dictionary to DataFrame
genre_df = pd.DataFrame.from_dict(genre_count, orient='index', columns=['count'])
genre_df = genre_df.sort_values(by='count', ascending=False)

# Create a bar chart
plt.figure(figsize=(10, 6))
genre_df.plot(kind='bar', legend=None)
plt.title('Distribution of Movie Genres')
plt.xlabel('Genre')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.show()

"""# Point B

Bagaimana distribusi kelompok rating (users_rating) pada film-film dalam dataset ini? Buat histogram atau density plot untuk menunjukkan distribusi rating.
"""

plt.figure(figsize=(10, 6))
plt.hist(df['users_rating'], bins=20, color='slategrey', edgecolor='black', density=True)
plt.title('Distribusi Rating Pengguna')
plt.xlabel('Rating Pengguna')
plt.ylabel('Densitas')
plt.grid(axis='y')
plt.tight_layout()
plt.show()

"""# Point C

Siapa direktur dengan jumlah film terbanyak? Buat pie chart untuk menunjukkan beberapa direktur terbaik.
"""

#LaluAldo
director_counts = df['directors'].value_counts()
top_directors = director_counts.head(5)  # Change the number as needed
plt.figure(figsize=(2, 2))
plt.pie(top_directors, labels=top_directors.index, autopct='%1.1f%%', startangle=140)
plt.title('Top 5 Direktur dengan Jumlah Film Terbanyak')
plt.show()

"""# Point D

Tampilkan 10 film dengan rating tertinggi! buat bar chart untuk memvisualisasikan rating film-film tersebut.
"""

#LaluAldo
top_rated_movies = df.nlargest(10, 'users_rating')
plt.figure(figsize=(10, 6))
plt.barh(top_rated_movies['title'], top_rated_movies['users_rating'], color='green')
plt.title('10 Film dengan Rating Tertinggi')
plt.xlabel('Rating')
plt.ylabel('Film')
plt.gca().invert_yaxis()  # Invert y-axis to have the highest rated movie on top
plt.show()

"""# Point E

Kesimpulan dari hasil analisis di atas.
"""

print("""Kesimpulan
- Distribusi genre film menunjukkan bahwa Genre Drama adalah genre yang mendominasi tontonan masyarakat Indonesia, dengan perbedaan yang hampir mencapai 25% dari posisi kedua, yaitu Genre Comedy, diikuti oleh Genre
  Horror yang berada di urutan ke-3
- Distribusi kelompok Rating menunjukkan bahwa film Indonesia memiliki kualitas yang cukup baik, namun adapun film-film yang memiliki kualitas yang kurang baik ataupun bisa dibilang 'Jelek'.
- Direktur dengan jumlah film terbanyak dipegang oleh Nayato Fio Nuala yang menyutradarai film Drama, seperti Heart 2 Heart, dan film Horror, seperti Kereta Hantu Mangarai, dengan rata-rata rating film yang
  disutradarainya adalah 4.8, dengan Rating tertinggi dipegang oleh Heart 2 Heart dengan Rating 8.4/10 dan Rating Terendah dipegang oleh Malam Jum'at Kliwon dengan Rating 2.1/10
- 10 Film dengan rating tertinggi adalah
  1. Horas Amang : Tiga Bulan Untuk Selamanya yang disutradarai oleh Irham Acho Bahtiar dan Steve R.R. Wantania
  2. Salisiah Adaik yang disutradarai oleh Ferdinand Almi
  3. Anak Garuda yang disutradarai oleh Faozan Rizal dan Verdi Solaiman
  4. Jelita Sejuba : Mencintai Kestaria Negara yang disutradarai oleh Ray Nayoan
  5. Turis Romantis yang disutradarai oleh Senoaji Julius
  6. Anak Muda Palsu yang disutradarai oleh Ihdar Nur
  7. Baco Becce yang disutradarai oleh Syahrir Arsyad Dini
  8. Surau dan Silek yang disutradarai oleh Arief Malinmudo
  9. Wage yang disutradarai oleh John de Rantau
  10. A Man Called Ahok yang disutradarai oleh Putrama Tuta
""")